### PR TITLE
Upgrade Docker dependencies

### PR DESCRIPTION
**Pull request by mgburns**
## Changes

**Merge #39 first**

- Update base PHP image ([richarvey/nginx-php-fpm 1.9.0](https://gitlab.com/ric_harvey/nginx-php-fpm/blob/master/docs/versioning.md#php-74), PHP 7.4)
- Switch pager from `more` to `less`
- Update install script to bypass cache on `docker build` so that we don't have to run `wp core update`
- Move docker configuration and scripts into a `docker` directory so that the deploy script doesn't get run on install
- Add server time zone configuration via `TZ` environment variable

(image of expected results)

## How To Test

1. Run `./bin/install` and `./bin/start`
2. Confirm that PHP 7.4.2 is running (`docker-compose exec wordpress php --version`)
3. Confirm that the latest version of WordPress (5.3.2) is installed (`./bin/wp core version`)
4. Confirm that the pager works for CLI commands (e.g. `./bin/wp help`)

### CODE REVIEW

**Comment by bchiang7** [comment]
@mgburns works for me! Since we moved the `conf` and `scripts` folder into the `docker` directory, we should update places that are referring to them right?  Like in the `docker-compose` and multisite docs?

**Comment by mgburns** [comment]
@bchiang7 Yes! I thought I caught them all, did I miss one?

**Comment by bchiang7** [comment]
@mgburns Yeah, the comment on line 61 in `docker-compose.yml` and line 100 in `multisite.md`

Is the setup script still being used?

**Comment by mgburns** [comment]
@bchiang7 Good catch, thank you! Just pushed a fix.

And yeah, setup script has been moved into `./docker/scripts`. I didn't like the Docker init script in the same directory as the deploy script. I realized that `richarvey/nginx-php-fpm` was automatically executing scripts in that directory on container start:
https://gitlab.com/ric_harvey/nginx-php-fpm/blob/master/docs/repo_layout.md#scripts

It didn't have the right env vars in place to actually deploy, but still shouldn't have been happening.

**Pull request merged**
