### PR TITLE
Merciless raid of PHPStan :)

### PR DESCRIPTION
**Pull request by szepeviktor**
## Changes

Fix types

🖼️

All 🐛-s must crawl away↗️

## How To Test

`vendor/bin/phpstan analyze`

Could be added to CI.

## TODOs:

Add types inside arrays

### CODE REVIEW

**Comment by mgburns** [comment]
Thanks for the contribution, @szepeviktor! Will take a closer look next week when we're back from holiday.

**Comment by mgburns** [comment]
@szepeviktor Thanks again for the contribution!

A few questions from my local testing...

- Looks like PHPStan pretty hungry -- I'm getting memory errors when attempting to run it without bumping up the limit to 256M:
    
    ```
    docker-compose exec -w /var/www/html/wp-content/themes/skela wordpress ./vendor/bin/phpstan analyze --memory-limit 256M
    ```
    
    Should that be necessary? Could it be defined via configuration instead?
- Anything special we should know re: those ACF stubs? My biggest concern is keeping them in sync with the plugin when it gets upgraded, and I'm not sure how actively maintained those stubs are.

**Comment by szepeviktor** [comment]
>     * Should that be necessary? Could it be defined via configuration instead?

No, it need a command line option. Alternatively you may revert PHP CLI's `max_memory` to -1

> those ACF stubs? My biggest concern is keeping them in sync with the plugin when it gets upgraded, and I'm not sure how actively maintained those stubs are.

ACF does not introduce new public functions frequently.
As I see in the wild: only `get_filed` is used.

**Comment by szepeviktor** [comment]
Thank you.

**Pull request merged**
